import Head from "next/head"
import Image from "next/image"
import { checkout } from "../../checkout"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Our Charity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
            <p>Donate here</p>
            <button onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1N2gLlAy6kbtVnGKmvjkxdgC",
                    quantity: 1
                  }
                ]
              })
            })}>Donate here!</button>
      </main>
    </div>
  )
}

















// import Image from 'next/image'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <main
//       className={`flex min-h-screen flex-col items-center justify-between p-24 ${inter.className}`}
//     >
//       <p>donate now</p>
//     </main>
//   )
// }
